### ISSUE TITLE
Consider changing the name of some configuration options

### ISSUE THREAD

**Issue by javiereguiluz** [enekochan/QRCodeBundle#1]
Thanks for publishing this bundle. After reading the README file, I find some option names confusing. Specifically, these are the changes that I'd make:
- `png_maximun_size` has a typo. It should be `png_maximum_size`
- `full_url` is usually called `absolute_url`
- `http_s_max_age` looks like a very unconvenient option name. I think this should be `https_max_age`

**Comment by ghost** [comment]
Thanks! You are 100% right, I'll change them all as you said.

**Comment by ghost** [comment]
Done in bf0646e0679e3da9937993530cdce118344ed40b
